// <auto-generated />
using System;
using BackEndAluguel.Infrastructure.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEndAluguel.Infrastructure.Migrations
{
    [DbContext(typeof(AluguelDbContext))]
    [Migration("20260429125932_MigracaoInicial")]
    partial class MigracaoInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.Apartamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("AtualizadoEm");

                    b.Property<string>("Bloco")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("")
                        .HasColumnName("Bloco");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("CriadoEm");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Numero");

                    b.Property<bool>("Ocupado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("Ocupado");

                    b.HasKey("Id");

                    b.HasIndex("Numero", "Bloco")
                        .IsUnique()
                        .HasDatabaseName("IX_Apartamentos_Numero_Bloco")
                        .HasFilter("[Bloco] IS NOT NULL");

                    b.ToTable("Apartamentos", (string)null);
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.Configuracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("KwhValor")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ValorAgua")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Configuracoes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CriadoEm = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            KwhValor = 0.0m,
                            ValorAgua = 0.0m
                        });
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.ContratoInquilino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("InquilinoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeOriginalArquivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoConteudo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("InquilinoId")
                        .HasDatabaseName("IX_ContratosInquilino_InquilinoId");

                    b.ToTable("ContratosInquilino", (string)null);
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.Dependente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<int>("EstadoCivil")
                        .HasColumnType("int");

                    b.Property<Guid>("InquilinoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OrgaoEmissor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Rg")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("IX_Dependentes_Cpf");

                    b.HasIndex("InquilinoId");

                    b.ToTable("Dependentes", (string)null);
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.Fatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("AtualizadoEm");

                    b.Property<string>("CobrancaAsaasId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CobrancaAsaasId");

                    b.Property<string>("CodigoPix")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("CodigoPix");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("CriadoEm");

                    b.Property<DateOnly>("DataLimitePagamento")
                        .HasColumnType("date")
                        .HasColumnName("DataLimitePagamento");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("date")
                        .HasColumnName("DataPagamento");

                    b.Property<Guid>("InquilinoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("InquilinoId");

                    b.Property<decimal?>("KwAtual")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("KwAtual");

                    b.Property<decimal?>("KwMesAnterior")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("KwMesAnterior");

                    b.Property<decimal?>("KwhValor")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("KwhValor");

                    b.Property<string>("MesReferencia")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)")
                        .HasColumnName("MesReferencia");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<decimal>("ValorAgua")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("ValorAgua");

                    b.Property<decimal>("ValorAluguel")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorAluguel");

                    b.Property<decimal>("ValorLuz")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("ValorLuz");

                    b.HasKey("Id");

                    b.HasIndex("InquilinoId", "MesReferencia")
                        .IsUnique()
                        .HasDatabaseName("IX_Faturas_InquilinoId_MesReferencia");

                    b.ToTable("Faturas", (string)null);
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.GastoManutencao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApartamentoId");

                    b.ToTable("GastosManutencao", (string)null);
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.Inquilino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("ApartamentoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ApartamentoId");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("AtualizadoEm");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("Cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2")
                        .HasColumnName("CriadoEm");

                    b.Property<DateOnly>("DataEntrada")
                        .HasColumnType("date")
                        .HasColumnName("DataEntrada");

                    b.Property<DateOnly>("DataVencimentoContrato")
                        .HasColumnType("date")
                        .HasColumnName("DataVencimentoContrato");

                    b.Property<string>("DiasAlertaVencimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DiasAlertaVencimento");

                    b.Property<decimal>("Garagem")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("Garagem");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NomeCompleto");

                    b.Property<int>("QuantidadeMoradores")
                        .HasColumnType("int")
                        .HasColumnName("QuantidadeMoradores");

                    b.Property<decimal>("ValorAluguel")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorAluguel");

                    b.HasKey("Id");

                    b.HasIndex("ApartamentoId");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("IX_Inquilinos_Cpf");

                    b.ToTable("Inquilinos", (string)null);
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.ContratoInquilino", b =>
                {
                    b.HasOne("BackEndAluguel.Domain.Entidades.Inquilino", "Inquilino")
                        .WithMany()
                        .HasForeignKey("InquilinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inquilino");
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.Dependente", b =>
                {
                    b.HasOne("BackEndAluguel.Domain.Entidades.Inquilino", "Inquilino")
                        .WithMany("Dependentes")
                        .HasForeignKey("InquilinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inquilino");
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.Fatura", b =>
                {
                    b.HasOne("BackEndAluguel.Domain.Entidades.Inquilino", "Inquilino")
                        .WithMany("Faturas")
                        .HasForeignKey("InquilinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inquilino");
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.GastoManutencao", b =>
                {
                    b.HasOne("BackEndAluguel.Domain.Entidades.Apartamento", "Apartamento")
                        .WithMany("GastosManutencao")
                        .HasForeignKey("ApartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartamento");
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.Inquilino", b =>
                {
                    b.HasOne("BackEndAluguel.Domain.Entidades.Apartamento", "Apartamento")
                        .WithMany("Inquilinos")
                        .HasForeignKey("ApartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apartamento");
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.Apartamento", b =>
                {
                    b.Navigation("GastosManutencao");

                    b.Navigation("Inquilinos");
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.Inquilino", b =>
                {
                    b.Navigation("Dependentes");

                    b.Navigation("Faturas");
                });
#pragma warning restore 612, 618
        }
    }
}
