// <auto-generated />
using System;
using BackEndAluguel.Infrastructure.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEndAluguel.Infrastructure.Migrations
{
    [DbContext(typeof(AluguelDbContext))]
    partial class AluguelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.Apartamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("AtualizadoEm");

                    b.Property<string>("Bloco")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("")
                        .HasColumnName("Bloco");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("CriadoEm");

                    b.Property<Guid>("HostId")
                        .HasColumnType("TEXT")
                        .HasColumnName("HostId");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("Numero");

                    b.Property<bool>("Ocupado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("Ocupado");

                    b.HasKey("Id");

                    b.HasIndex("HostId", "Numero", "Bloco")
                        .IsUnique()
                        .HasDatabaseName("IX_Apartamentos_HostId_Numero_Bloco");

                    b.ToTable("Apartamentos", (string)null);
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.Configuracao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChavePix")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("CidadeRecebedorPix")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HostId")
                        .HasColumnType("TEXT")
                        .HasColumnName("HostId");

                    b.Property<decimal>("KwhValor")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("MensagemPadraoWhatsapp")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeRecebedorPix")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroWhatsappLocador")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorAgua")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("WalletIdAsaas")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HostId")
                        .IsUnique()
                        .HasDatabaseName("IX_Configuracoes_HostId");

                    b.ToTable("Configuracoes", (string)null);
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.ContratoInquilino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InquilinoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeOriginalArquivo")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoConteudo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InquilinoId")
                        .HasDatabaseName("IX_ContratosInquilino_InquilinoId");

                    b.ToTable("ContratosInquilino", (string)null);
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.Dependente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstadoCivil")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("InquilinoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrgaoEmissor")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rg")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("IX_Dependentes_Cpf");

                    b.HasIndex("InquilinoId");

                    b.ToTable("Dependentes", (string)null);
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.Fatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("AtualizadoEm");

                    b.Property<string>("CobrancaAsaasId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("CobrancaAsaasId");

                    b.Property<string>("CodigoPix")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("CodigoPix");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("CriadoEm");

                    b.Property<DateOnly>("DataLimitePagamento")
                        .HasColumnType("TEXT")
                        .HasColumnName("DataLimitePagamento");

                    b.Property<DateOnly?>("DataPagamento")
                        .HasColumnType("TEXT")
                        .HasColumnName("DataPagamento");

                    b.Property<Guid>("HostId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InquilinoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("InquilinoId");

                    b.Property<decimal?>("KwAtual")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("KwAtual");

                    b.Property<decimal?>("KwMesAnterior")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT")
                        .HasColumnName("KwMesAnterior");

                    b.Property<decimal?>("KwhValor")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT")
                        .HasColumnName("KwhValor");

                    b.Property<string>("MesReferencia")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT")
                        .HasColumnName("MesReferencia");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Status");

                    b.Property<decimal>("ValorAgua")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("ValorAgua");

                    b.Property<decimal>("ValorAluguel")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("ValorAluguel");

                    b.Property<decimal>("ValorGaragem")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("ValorGaragem");

                    b.Property<decimal>("ValorLuz")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("ValorLuz");

                    b.HasKey("Id");

                    b.HasIndex("InquilinoId", "MesReferencia")
                        .IsUnique()
                        .HasDatabaseName("IX_Faturas_InquilinoId_MesReferencia");

                    b.ToTable("Faturas", (string)null);
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.GastoManutencao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApartamentoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApartamentoId");

                    b.ToTable("GastosManutencao", (string)null);
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.Host", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .IsFixedLength();

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenConfirmacao")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TokenExpiracaoConfirmacao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TokenConfirmacao")
                        .IsUnique()
                        .HasFilter("[TokenConfirmacao] IS NOT NULL");

                    b.ToTable("Hosts", (string)null);
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.Inquilino", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<Guid>("ApartamentoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ApartamentoId");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("AtualizadoEm");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT")
                        .HasColumnName("Cpf");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT")
                        .HasColumnName("CriadoEm");

                    b.Property<DateOnly>("DataEntrada")
                        .HasColumnType("TEXT")
                        .HasColumnName("DataEntrada");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("TEXT")
                        .HasColumnName("DataNascimento");

                    b.Property<DateOnly>("DataVencimentoContrato")
                        .HasColumnType("TEXT")
                        .HasColumnName("DataVencimentoContrato");

                    b.Property<string>("DiasAlertaVencimento")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DiasAlertaVencimento");

                    b.Property<int>("EstadoCivil")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EstadoCivil");

                    b.Property<decimal>("Garagem")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("Garagem");

                    b.Property<Guid>("HostId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("NomeCompleto");

                    b.Property<string>("OrgaoEmissor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("OrgaoEmissor");

                    b.Property<int>("QuantidadeMoradores")
                        .HasColumnType("INTEGER")
                        .HasColumnName("QuantidadeMoradores");

                    b.Property<string>("Rg")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("Rg");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("Telefone");

                    b.Property<decimal>("ValorAluguel")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("ValorAluguel");

                    b.HasKey("Id");

                    b.HasIndex("ApartamentoId");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("IX_Inquilinos_Cpf");

                    b.ToTable("Inquilinos", (string)null);
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.Apartamento", b =>
                {
                    b.HasOne("BackEndAluguel.Domain.Entidades.Host", null)
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.Configuracao", b =>
                {
                    b.HasOne("BackEndAluguel.Domain.Entidades.Host", null)
                        .WithMany()
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.ContratoInquilino", b =>
                {
                    b.HasOne("BackEndAluguel.Domain.Entidades.Inquilino", "Inquilino")
                        .WithMany()
                        .HasForeignKey("InquilinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inquilino");
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.Dependente", b =>
                {
                    b.HasOne("BackEndAluguel.Domain.Entidades.Inquilino", "Inquilino")
                        .WithMany("Dependentes")
                        .HasForeignKey("InquilinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inquilino");
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.Fatura", b =>
                {
                    b.HasOne("BackEndAluguel.Domain.Entidades.Inquilino", "Inquilino")
                        .WithMany("Faturas")
                        .HasForeignKey("InquilinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inquilino");
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.GastoManutencao", b =>
                {
                    b.HasOne("BackEndAluguel.Domain.Entidades.Apartamento", "Apartamento")
                        .WithMany("GastosManutencao")
                        .HasForeignKey("ApartamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartamento");
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.Inquilino", b =>
                {
                    b.HasOne("BackEndAluguel.Domain.Entidades.Apartamento", "Apartamento")
                        .WithMany("Inquilinos")
                        .HasForeignKey("ApartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Apartamento");
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.Apartamento", b =>
                {
                    b.Navigation("GastosManutencao");

                    b.Navigation("Inquilinos");
                });

            modelBuilder.Entity("BackEndAluguel.Domain.Entidades.Inquilino", b =>
                {
                    b.Navigation("Dependentes");

                    b.Navigation("Faturas");
                });
#pragma warning restore 612, 618
        }
    }
}
